version: '3.7'

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: ["bash", "-c", "python manage.py runserver 0.0.0.0:8000"]
    user: root
    environment: 
      - DB_HOST=mysql-db
      - DB_NAME=app
      - DB_USER=root
      - DB_PASS=supersecretpassword
    depends_on:
      - db
      - redis

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - mysql-db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=mysql-db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=supersecretpassword
      - MYSQL_ROOT_PASSWORD=supersecretpassword

  redis:
    restart: always
    image: redis:5.0.7
    ports:
      - "6739:6379"
    volumes:
      - redisdata:/data

volumes:
  mysql-db:
  redisdata:
