version: '3.7'

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: "./start.sh"
    user: root
    environment: 
      - DB_HOST=mysql-db
      - DB_USER=root
      - DB_PASS=supersecretpassword
    depends_on:
      - mysql
      - redis
      - elasticsearch
      - mongo

  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysql-db:/var/lib/mysql

    environment:
      - MYSQL_DATABASE=mysql-db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=supersecretpassword
      - MYSQL_ROOT_PASSWORD=supersecretpassword

  redis:
    image: redis:5.0.7
    restart: always
    ports:
      - "6739:6379"
    volumes:
      - redisdata:/data

  elasticsearch:
    image: elasticsearch:6.8.6
    restart: always
    ports:
      - "9200:9200"
    volumes:
      - elasticdata:/usr/share/elasticsearch/data
    environment:
      - cluster.name=docker-cluster

  mongo:
    image: mongo:3.4-xenial
    restart: always
    ports:
      - "27017-27019:27017-27019"
    volumes:
      - mongodbdata:/data/db
    environment:
      MONGO_INITDB_DATABASE: mongodb
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null


volumes:
  mysql-db:
  redisdata:
  elasticdata:
  mongodbdata:
